language: go

os:
  - linux
  - windows

go:
  - 1.11.x
  - 1.12.x

# Building on Windows for 1.12 we get
#   travis_install_go_dependencies 1.12.x -v
#   go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;

addons:
  apt:
    packages:
      - rpm

env:
  - GO111MODULE=on

# Tell Travis not to do magic on our behalf
# See https://arslan.io/2018/08/26/using-go-modules-with-vendor-support-on-travis-ci/
install: true

script:
  - go install github.com/go-task/task/cmd/task
  - task ci

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
